### ISSUE TITLE
Double slash commands do not work

### ISSUE THREAD

**Issue by PanoptesDreams** [PrometheuzzZ/InventoryBinds#1]
Using a double slash command like //wand does not work.

The in-game feedback is 'this command does not exist'.

I'm assuming what is happening is the extra slashes are being stripped away.

**Comment by PrometheuzzZ** [comment]
You're right, fixed it

**Comment by PrometheuzzZ** [comment]
Update the mod and check if it works

**Comment by PanoptesDreams** [comment]
Fixed, it works!
