### ISSUE TITLE
If used with OptiFabric, it gives an error about the inability to load resources pack

### ISSUE THREAD

**Issue by Xleby4ek** [PrometheuzzZ/InventoryBinds#2]
Minecraft: 1.20.1
OptiFabric: v1.13.25
Mod Version: 1.1

**Comment by PrometheuzzZ** [comment]
can I see the crash log?

**Comment by PrometheuzzZ** [comment]
Чел ты серьезно? Юзай содиум, какой ***ть оптифабрик, юзай содиум

**Comment by PrometheuzzZ** [comment]
![изображение_2024-01-14_211516525](https://github.com/PrometheuzzZ/InventoryBinds/assets/21082056/1f18902c-c289-4b2f-a7d8-62e773c4872d)

**Comment by Xleby4ek** [comment]
What kind of a cringe did you answer me
I literally don't want to use soda because many resource packs don't work in it, even with mods to support them. I just reported a bug, and you answered bruuuuh (Что за кринж ты мне ответил
Я буквально не хочу юзать содиум из-за того, что в нём не работают многие ресурс паки, даже с модами на их поддержку. Я просто сообщил о баге, а ты так ответил bruuuuh)

**Comment by PrometheuzzZ** [comment]
> What kind of a cringe did you answer me I literally don't want to use soda because many resource packs don't work in it, even with mods to support them. I just reported a bug, and you answered bruuuuh (Что за кринж ты мне ответил Я буквально не хочу юзать содиум из-за того, что в нём не работают многие ресурс паки, даже с модами на их поддержку. Я просто сообщил о баге, а ты так ответил bruuuuh)

I am not negative, but unfortunately this will not be fixed, because as far as I could understand, this is an optical factory problem.

(Я без негатива, но соре это не будет фиксится, потому что насколько я смог понять это проблема оптифабрика. )
