### ISSUE TITLE
(Feature Request) Hide Settings Button

### ISSUE THREAD

**Issue by Alasofia** [PrometheuzzZ/InventoryBinds#7]
Is it possible to add a config option to disable the settings button?
I've added binds for my server's modpack but would prefer to leave the (effectively useless) settings button hidden.

**Comment by Alasofia** [comment]
I only just realized that the 1.20.4 version is not up to date with 1.21, so this might be implemented. Either way, I would really appreciate it being added for 1.20.4 :)

**Comment by PrometheuzzZ** [comment]
I'll do it now

**Comment by PrometheuzzZ** [comment]
I also add settings for the disable button, adding new binds and editing binds.


"bind_editor_enabled":"true"
"new_bind_button_enabled":"true"

**Comment by PrometheuzzZ** [comment]
https://modrinth.com/mod/inventory-binds/version/2.2-1.20.4

**Comment by Alasofia** [comment]
You are amazing. Thank you!
