### ISSUE TITLE
new version is bind button missing

### ISSUE THREAD

**Issue by Gyeongb1n** [PrometheuzzZ/InventoryBinds#8]
title
![1](https://github.com/user-attachments/assets/0fc8dc9a-f288-4ea5-8acd-19f1e109d35b)

**Comment by PrometheuzzZ** [comment]
delete old config file

**Comment by Gyeongb1n** [comment]
Thank you. Also, can you update it so that you can add icons to the left of the inventory or freely like NEU? (Using translator)
![1](https://github.com/user-attachments/assets/fddc88d8-5a2a-4243-9e83-219905d8d2bc)
Right now the mod is too limited to add many icons.

**Comment by PrometheuzzZ** [comment]
what is the practical point, on the right you can add an unlimited number of binds, and on the left they can cause display problems in different inventories

> Thank you. Also, can you update it so that you can add icons to the left of the inventory or freely like NEU? (Using translator) ![1](https://private-user-images.githubusercontent.com/82765287/391203837-fddc88d8-5a2a-4243-9e83-219905d8d2bc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MjkwODIsIm5iZiI6MTczMjkyODc4MiwicGF0aCI6Ii84Mjc2NTI4Ny8zOTEyMDM4MzctZmRkYzg4ZDgtNWEyYS00MjQzLTllODMtMjE5OTA1ZDhkMmJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDAxMDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMDU0ZWQ4ZjkxNmNjODU5YWQ2M2VjNmYzMzJlODFjNjA4NGE1MjM0NmI2MzM3NGYxNWU3YmVkMDUxZjgwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.z8k3pqWddJtK5wNSttp6vRsyXD63xlTVh7lv7tYzjWY) Right now the mod is too limited to add many icons.
